# Repository Guidelines

## Project Structure & Module Organization
- `app/` — Next.js App Router pages (`page.tsx`, `layout.tsx`).
- `components/` — Reusable React UI components (PascalCase files).
- `db/schema.ts` — Drizzle ORM schema source of truth.
- `drizzle/` — SQL migrations and metadata snapshot generated by Drizzle Kit.
- `seed/` — CSV seed data for Supabase imports.
- `lib/`, `hooks/` — Utilities and React hooks.
- `public/` — Static assets.

## Build, Test, and Development Commands
- `pnpm dev` — Run Next.js dev server.
- `pnpm build` — Production build.
- `pnpm start` — Start built app.
- `pnpm lint` — Lint codebase with ESLint.
- `pnpm drizzle:generate` — Generate SQL from `db/schema.ts`.
- `pnpm drizzle:push` — Apply migrations to the configured database.
- `pnpm drizzle:studio` — Open Drizzle Studio for DB inspection.

## Coding Style & Naming Conventions
- Language: TypeScript + React function components.
- Follow ESLint rules; run `pnpm lint` before pushing.
- Indentation 2 spaces; avoid unused exports; prefer named exports.
- Components: PascalCase (`components/OrderCard.tsx`).
- App routes follow Next.js conventions (`app/(group)/feature/page.tsx`).

## Testing Guidelines
- No test framework is configured yet.
- If adding tests, prefer Vitest + React Testing Library.
- Place tests next to sources as `*.test.ts[x]`; keep them fast and deterministic.
- Add a `test` script to `package.json` when introducing tests.

## Commit & Pull Request Guidelines
- Use Conventional Commits: `feat:`, `fix:`, `chore:`, `refactor:`, `docs:`, `ci:`.
- Keep subject ≤72 chars; include scope when helpful: `feat(db): add orders index`.
- PRs must include: purpose, key changes, screenshots (UI), and linked issues.
- Keep diffs focused; update related seeds/migrations when schema changes.

## Security & Configuration Tips
- Environment variables live in `.env.local` (ignored by Git). Do not commit secrets.
- Required vars: `NEXT_PUBLIC_SUPABASE_URL`, `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY`, `DATABASE_URL`.
- When changing schema: update `db/schema.ts`, regenerate migrations, and adjust `seed/` CSVs accordingly.

## Other
- KISS / DRY / YAGNI：保持简单、消除重复、不要过度设计。
- 边界优先：输入校验、空值处理、超时与重试策略。
- 组件封装：前端组件需要封装到 components/目录下，避免页面代码冗余
- 中文输出
